[tool.poetry]
name = "skypro-homeworks-05-postgres"
version = "0.1.0"
description = ""
authors = ["Victor Sadykov"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
